name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm 7
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Dependencies
        shell: bash
        run: pnpm i

      - name: Build
        shell: bash
        run: pnpm build

      - name: Install turbo-version
        run: pnpm i

      - name: Setting up Git user 🤖
        shell: bash
        run: git config user.email "juciano@outlook.com.br" && git config user.name "jucian0"

      - name: TurboVersion
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        shell: bash
        run: pnpm turbov
